import datetime
currentdate=datetime.datetime.now()
def print_bill_to_console(purchased_items):
    print("-----------------------------------------------------------------------------------------------")
    print("For Bill Generation you will have to enter the your details first.")
    print("-----------------------------------------------------------------------------------------------")
    print("\n")
    #print("\t \t \t \t Your item is rented")

    grand_total=0
    name=input("Enter your name: ")
    print("\n")
    phone=input("Enter your phone number: ")
    print("\n")
    print("\n")
    print("\t \t \t \tArchana Rental")
    print("\n")
    print("\t \t \t \tKathmandu")
    print("\n")
    print("-----------------------------------------------------------------------------------------------")
    print("Customer Details:")
    print("-----------------------------------------------------------------------------------------------")
    print("\n")
    print("Name of the Customer: " + str(name))
    print("Contact number: " + str(phone))
    print("Date and Time of purchase:", currentdate)
    print("-----------------------------------------------------------------------------------------------")
    print("\n")
    print("Purchase details are: ")
    print("-----------------------------------------------------------------------------------------------")
    print("Item Name\t\t Total Quantity\t\t Unit Price\t\t Total")
    print("-----------------------------------------------------------------------------------------------")
    # print(purchased_items)
    for item in purchased_items:
        grand_total += int(item[3])
        print(item[0], "\t\t", item[1], "\t\t", item[2], "\t\t", "$", item[3])
    print("-----------------------------------------------------------------------------------------------")
    print("Grand Total: $" + str(grand_total))
    print("Note: Fine cost will be added to the grand total in case of delay")
    print("$50 per day.")
    print("-----------------------------------------------------------------------------------------------")
    generate_bill_to_file(name, phone,purchased_items, grand_total)


def generate_bill_to_file(name,phone,purchased_items, grand_total):
    # print(purchased_items)
    filename = name + "_" + phone + "_bill.txt"
    with open(filename, "w") as file:
        file.write("\n")
        file.write("\t \t \t \tArchana Rental\n")
        file.write("\n")
        file.write("\t \t \t \t Kathmandu\n")
        file.write("\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("Customer Details:\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("\n")
        file.write("Name of the Customer: " + str(name) + "\n")
        file.write("Contact number: " + str(phone) + "\n")
        file.write("Date and Time of purchase: " + str(currentdate) + "\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("\n")
        file.write("Purchase details are: \n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("Item Name\t\t Total Quantity\t\t Unit Price\t\t \t\t Brand\t Total\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        for item in purchased_items:
            # print(item)
            file.write(str(item[0]) + "\t\t\t\t\t" + str(item[1]) + "\t\t" + item[2]+"\t\t\t"+ item[4] + "\t\t" + "$" + str(item[3])  + "\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("Grand Total: $" + str(grand_total) + "\n")
        file.write("Note: Fine cost will be added to the grand total in case of delay\n")
        file.write("$50 per day.\n")
    print("Bill has been written to the file:", filename)



def print_bill_to_console_fine(purchased_items):
    print("-----------------------------------------------------------------------------------------------")
    print("For Bill Generation you will have to enter the your details first.")
    print("-----------------------------------------------------------------------------------------------")
    # print("\n")
    total=0
    name=input("Enter your name: ")
    # print("\n")
    phone=input("Enter your phone number: ")
    while True:
        try:
            dayslate=int(input("Enter days late: "))
            break
        except ValueError:
            print("Enter days late 'In Number': ")
    print("\n")
    # print("\n")
    print("-----------------------------------------------------------------------------------------------")
    print("\t \t \t \tArchana Rental")
    print("\n")
    print("\t \t \t \tKathmandu")
    print("\n")
    print("-----------------------------------------------------------------------------------------------")
    print("Customer Details:")
    print("-----------------------------------------------------------------------------------------------")
    # print("\n")
    print("Name of the Customer: " + str(name))
    print("Contact number: " + str(phone))
    print("Date and Time of purchase:", currentdate)
    print("-----------------------------------------------------------------------------------------------")
    print("\n")
    print("Purchase details are: ")
    print("-----------------------------------------------------------------------------------------------")
    print("Item Name\t\t Total Quantity\t\t Unit Price\t\t Total")
    print("-----------------------------------------------------------------------------------------------")
    # print(purchased_items)
    for item in purchased_items:
        total+=int(item[3])
        # print(item)
        print(item[0], "\t\t", item[1], "\t\t", item[2], "\t\t", "$", item[3])
    print("-----------------------------------------------------------------------------------------------")
    print("Total: $" + str(total))
    fine = dayslate * 50
    print("Fine : $" + str(fine))
    f_total = total + fine
    print("Grand Total (including fine): $" + str(f_total))
    print("Note: Fine cost will be added to the grand total in case of delay")
    print("$50 per day.")
    generate_bill_to_file_fine(name, phone,purchased_items, total, f_total)
    
def generate_bill_to_file_fine(name,phone,purchased_items, total, f_total):
    filename = name + "_" + phone + "_bill.txt"
    with open(filename, "w") as file:
        file.write("\n")
        file.write("\t \t \t \tArchana Rental\n")
        file.write("\n")
        file.write("\t \t \t Kathmandu\n")
        file.write("\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("Item Details:\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("\n")
        file.write("Name of the Customer: " + str(name) + "\n")
        file.write("Contact number: " + str(phone) + "\n")
        file.write("Date and Time of purchase: " + str(currentdate) + "\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("\n")
        file.write("Purchase details are: \n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("Item Name\t\t Total Quantity\t\t Unit Price\t\t \t\t Brand\t Total\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        for item in purchased_items:
            # print(item)
            file.write(str(item[0]) + "\t\t\t\t\t" + str(item[1]) + "\t\t" + item[2]+"\t\t\t"+ item[4] + "\t\t" + "$" + str(item[3])  + "\n")
        file.write("-----------------------------------------------------------------------------------------------\n")
        file.write("Total: $" + str(total) + "\n")
        file.write("Grand Total (including fine): $" + str(f_total) + "\n")
        file.write("Note: Fine cost will be added to the grand total in case of delay\n")
        file.write("$50 per day.\n")

    print("Bill has been written to the file:", filename)
    print("\n")

